server:
  port: 9004

spring:
  application:
    name: feign-hystrix

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#feign默认开启断路器,但目前这个版本不会，下面的配置必须写
feign:
  hystrix:
    enabled: true
