server:
  port: 8799

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          basedir: E:/ProgramData/git/SpringCloudConfig #本地地址
          uri: https://github.com/buyilihao/SpringCloudConfig.git #gitHub地址
          default-label: master #默认为master
          username: 
          password: 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
